language: node_js
node_js:
- node
deploy:
  provider: npm
  email: zater.systems@gmail.com
  api_key:
    secure: pmK5KCuat9zhQ87g/vGHUdMfmQhUtE6uQmLrUq5Stwb6u1fAGnhsuuc+QxTlBZZzkZnLoGHt9ZMz49DkIlz9tEJCIk0n2E/3yz4gAEpTK0yGg8MZv0q0s+Gf/9Oj1ZBBYx+2pfx8/EYf0RBOEJzOpXMjFrFCRbg8Ohu6BffRgiUWbejhc2GHY+tNkOabF9oB26N2U7kBFJGPUY0tjQGC0JbUHbxFnQg1VKb+zcHKFwku83g4qJZf8wJfEfPgjpf0wz/BMNlsNhvx1Y/8Fr6omjpZnOvAXsho2tYEb8egf5iD14g9VxfJMMEcJw5SkJeUaP6q/FvhwhMNzqBCONVP3OTTo4+NpAVHWXUwJsV88imr2WpDbtKd/armDezDamtBLVkesqCnvukbTIfVxwxHKogOD+eFmkMrQac23lFKrrlWsFVfCzsHeWOAV/hGGgf4OY9lPTSSy7i4i6G1UlCDrZcEuPOSt8QkKQ11NEyOL32I2yBCXeke/ZCMbU7w5b+otcpzRwYzc2dzWtGlCmmtRebzGqQQfjhzeBcsWJ1fCqK/C/TUlD3z34L86KKFoZnglLFXjRAXjyoDroA7KpY1pulM5CtB8jPIWrAYk04h48aTR5/FTjEXaeS/tz9zydVt/378hZBFP6oKstNeut7chiR1d3GJghgUHfMqBzAyzsc=
  on:
    tags: true
    repo: zater-systems/style-guide
